version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      -run:
          name: install dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          name: scan inamuu.com
          command: |
            python3 wpseku.py --url https://inamuu.com --verbose
